name: "AI PR Review"
description: "Reviews PRs using AI APIs"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: true
  project-name:
    description: "Name of the project (for project-specific prompts)"
    required: true
  openai-model:
    description: "OpenAI model to use"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
