name: 'AI PR Review'
description: 'Reviews PRs using AI APIs'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App private key'
    required: true
  installation-id:
    description: 'GitHub App installation ID'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  project-name:
    description: 'Name of the project (for project-specific prompts)'
    required: true
  openai-model:
    description: 'OpenAI model to use'
    required: true
  full-scan:
    description: 'Whether to scan the entire PR or just the diff'
    required: false
    default: 'false'
  enable-replies:
    description: 'Enable bot to reply to PR comments'
    required: false
    default: 'false'
  include-project-prompts-in-replies:
    description: 'Include project prompts in reply analysis'
    required: false
    default: 'false'
  only-first:
    description: 'Only allow one review per PR'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
